// 120 traits: each is { name, desc, flavor } — all in English
// Tiers: low (40), middle (40), high (20), s (10), random (10)
window.TRAITS = {
  low: [
    {name:"Night Sight", desc:"You discern shapes and movement in dim light.", flavor:"The dark is not empty to you."},
    {name:"Iron Stomach", desc:"Spoiled food and weak poisons barely affect you.", flavor:"You’ve tasted worse and lived to tell."},
    {name:"Keen Hearing", desc:"Distant sounds stand out more easily to you.", flavor:"Silence has layers; you hear them all."},
    {name:"Beastfriend", desc:"Animals react more calmly in your presence.", flavor:"Your heartbeat speaks a gentler tongue."},
    {name:"Herbwise", desc:"You recognize simple healing and poisonous plants.", flavor:"Leaves whisper remedies to careful eyes."},
    {name:"Restful Sleep", desc:"You recover faster even under rough conditions.", flavor:"Fatigue loosens its grip when you lie down."},
    {name:"Sense of Direction", desc:"You rarely lose your way.", flavor:"Every path leaves a taste on the wind."},
    {name:"Climber", desc:"You move sure-handed on trees, walls, and slopes.", flavor:"Stone and bark feel like old friends."},
    {name:"Instinct", desc:"You get a vague forewarning of danger.", flavor:"A chill runs ahead of the blade."},
    {name:"Gentle Demeanor", desc:"People tend to trust you more easily.", flavor:"Kindness turns locks better than keys."},
    {name:"Soft Step", desc:"Your steps are naturally quiet.", flavor:"Even your shadow treads lightly."},
    {name:"Improviser", desc:"You find simple fixes with scant materials.", flavor:"If it’s there, it’s useful—somehow."},
    {name:"Quick Mend", desc:"Minor injuries heal more quickly on you.", flavor:"Your flesh remembers wholeness."},
    {name:"Steady Stance", desc:"You rarely lose your balance.", flavor:"The ground keeps a promise beneath you."},
    {name:"Slender Build", desc:"You squeeze through tight gaps and spaces.", flavor:"You slip where others wedge."},
    {name:"Intimidating Gaze", desc:"Your stare unsettles some foes.", flavor:"Your eyes draw a line they hesitate to cross."},
    {name:"Sharp Nose", desc:"You smell smoke, blood, or toxins early.", flavor:"Scents sketch maps before sight arrives."},
    {name:"Nimble Fingers", desc:"Knots, tools, and small mechanisms favor you.", flavor:"Precision is a language your hands speak."},
    {name:"Composed", desc:"You stay calm under pressure.", flavor:"Storms pass; the center holds."},
    {name:"Balancing Act", desc:"You keep steady on beams, ropes, and ice.", flavor:"A breath, a step—then the world aligns."},
    {name:"Patient", desc:"Long waiting or watching comes easy.", flavor:"Time blinks first."},
    {name:"Tough Hide", desc:"You resist scratches and scrapes better.", flavor:"Your skin tells hardships to move along."},
    {name:"Practiced Swimmer", desc:"You move confidently in water.", flavor:"Water reads your strokes like poetry."},
    {name:"Clear Voice", desc:"Your words carry even through noise.", flavor:"Your voice cuts through the clamor."},
    {name:"Simple Remedy", desc:"Herbs and potions work slightly better on you.", flavor:"Healing finds a straight path in you."},
    {name:"Energy Sense", desc:"You feel when forces gather nearby.", flavor:"Invisible currents tickle your bones."},
    {name:"Will-Flame", desc:"Your mind resists small mental effects.", flavor:"A spark inside refuses to dim."},
    {name:"Thin Bloodline", desc:"A hidden heritage shows faint hints.", flavor:"Old echoes stir in your veins."},
    {name:"Spiritual Ear", desc:"You sometimes hear whispers beyond the world.", flavor:"Not all voices need lungs."},
    {name:"Spore Skin", desc:"Resistant to insects and tiny parasites.", flavor:"Biting things lose their appetite."},
    {name:"Bone Strength", desc:"Your bones are harder to break.", flavor:"Your frame was built for bad days."},
    {name:"Short Step", desc:"A reflex lets you sidestep in a split second.", flavor:"You’re already where the strike is not."},
    {name:"Icy Breath", desc:"Your breath chills small surfaces.", flavor:"Frost follows your sighs."},
    {name:"Spark Flicker", desc:"You can create tiny embers or sparks.", flavor:"Fire hums to your fingertips."},
    {name:"Ghost Glimpse", desc:"You sometimes see faint outlines of spirits.", flavor:"The world has margins; you notice them."},
    {name:"Skin Markings", desc:"Glowing sigils bloom on your skin at times.", flavor:"Your skin remembers constellations."},
    {name:"Wave Rider", desc:"You keep balance on boats and shifting decks.", flavor:"Waves bow to your footing."},
    {name:"Residual Pressure", desc:"You can project a faint mental push.", flavor:"A suggestion carried on a thought."},
    {name:"Shadow Inclination", desc:"You move instinctively in cover.", flavor:"Shade opens doors the sun cannot see."},
    {name:"Restless Energy", desc:"You stay active even with little sleep.", flavor:"Your candle burns without shrinking."}
  ],
  middle: [
    {name:"Quick Reflexes", desc:"You react faster than most.", flavor:"You move in the space between heartbeats."},
    {name:"Elemental Affinity", desc:"You have a natural tie to one element.", flavor:"One element calls your name—softly, constantly."},
    {name:"Iron Will", desc:"Your mind resists manipulation and illusion.", flavor:"Doubts crash and break against you."},
    {name:"Athletic", desc:"Your body is strongly trained.", flavor:"Discipline lives in your muscles."},
    {name:"Pain Tolerance", desc:"Injuries hinder you less.", flavor:"Pain is a milestone, not a wall."},
    {name:"Sure Aim", desc:"Ranged attacks land more reliably.", flavor:"Distance is just a courteous pause."},
    {name:"Silent Step", desc:"You move quietly on tricky ground.", flavor:"Even loose boards keep your secret."},
    {name:"Charismatic", desc:"Your presence captivates others.", flavor:"Attention leans toward you unbidden."},
    {name:"Silver Tongue", desc:"You persuade or deceive more easily.", flavor:"Words, well-placed, unlock iron doors."},
    {name:"Magic-Sensitive", desc:"You sense the presence of active magic.", flavor:"Your skin pricks where spells breathe."},
    {name:"Master of Herbs", desc:"You brew potions and poisons safely.", flavor:"Mortars sing when you grind."},
    {name:"Brave", desc:"Even mortal danger rarely shakes you.", flavor:"Fear arrives late to your bones."},
    {name:"Keen Eye", desc:"You spot distant details with clarity.", flavor:"Horizons hold fewer secrets for you."},
    {name:"Rugged Body", desc:"You endure hunger and cold longer.", flavor:"Harsh weather is an old companion."},
    {name:"Poison Resistant", desc:"Common toxins barely work on you.", flavor:"Venoms grow tired before you do."},
    {name:"Tactician", desc:"You read patterns and coordinate allies.", flavor:"Battles unfold like puzzles in your mind."},
    {name:"Shadow Friend", desc:"In darkness you’re nimbler and subtler.", flavor:"Dark places make room for you."},
    {name:"Combat Instinct", desc:"You notice openings in melee.", flavor:"Your blade remembers where to go."},
    {name:"Rapid Healer", desc:"Wounds seal noticeably faster.", flavor:"Your blood hates to linger outside."},
    {name:"Aura of Calm", desc:"People feel safer near you.", flavor:"You breathe, and the room steadies."},
    {name:"Tracker", desc:"You read tracks like open books.", flavor:"Footprints confess to you."},
    {name:"Precision Hands", desc:"Ideal for runes, locks, and fine work.", flavor:"Small tasks bloom under your touch."},
    {name:"Mental Flexibility", desc:"You adapt extremely quickly.", flavor:"You bend; you do not break."},
    {name:"Weapon Focus", desc:"With one weapon you’re exceptionally deadly.", flavor:"You and your chosen steel share a pulse."},
    {name:"Fighting Spirit", desc:"Injury drives you to peak output.", flavor:"Pain is the bell; you answer."},
    {name:"Protective Instinct", desc:"You snap to defend allies at once.", flavor:"Others’ safety triggers your stride."},
    {name:"Energy Control", desc:"You channel inner force into motion.", flavor:"Power threads through your sinew on command."},
    {name:"Will Pressure", desc:"Your will can briefly cow foes.", flavor:"A glance presses like a hand to the chest."},
    {name:"Soul Spark", desc:"Your strikes can touch spirits and illusions.", flavor:"Steel borrows a hint of the unseen."},
    {name:"Bloodline Awakened (Minor)", desc:"First signs of a heritage appear.", flavor:"The past stirs, asking for a future."},
    {name:"Dash Step", desc:"Short, lightning-quick movement.", flavor:"The ground blurs beneath your decision."},
    {name:"Energy Carapace (Latent)", desc:"Your body hardens for seconds.", flavor:"Power scales ripple beneath your skin."},
    {name:"Cursed Grip", desc:"Your touch slightly weakens objects or foes.", flavor:"Entropy listens to your fingers."},
    {name:"Cry of Will", desc:"Your shout ignites allies’ courage.", flavor:"Your voice lifts spines and steel alike."},
    {name:"Chain Instinct", desc:"Your flow is hard to interrupt.", flavor:"Momentum clings to you like a cloak."},
    {name:"Elemental Gleam", desc:"Your body shows brief elemental sparks.", flavor:"Embers, droplets, dust—your aura plays with them."},
    {name:"Spiritual Sense", desc:"You briefly perceive spirits or the unseen.", flavor:"Curtains thin when you focus."},
    {name:"Inner Focus", desc:"You hold extreme concentration briefly.", flavor:"Noise drifts to the shore; you stay at sea."},
    {name:"Energy Flow", desc:"You regenerate energy more quickly at rest.", flavor:"Stillness refills your river."},
    {name:"Honed Senses", desc:"All senses are slightly heightened.", flavor:"The world turns the volume up for you."}
  ],
  high: [
    {name:"Lightning Reaction", desc:"You almost anticipate movements.", flavor:"Motion telegraphs itself to your bones."},
    {name:"Iron Skin", desc:"Your body is tough as armor.", flavor:"Blows glance like rain off stone."},
    {name:"Magic Resistance", desc:"Spells have a reduced effect on you.", flavor:"Enchantment frays on contact."},
    {name:"Battle Trance", desc:"The more you’re hurt, the stronger you fight.", flavor:"Wounds are fuel; you burn bright."},
    {name:"Shadow Shroud", desc:"You nearly merge with darkness.", flavor:"You become the space between lanterns."},
    {name:"Regeneration", desc:"Even deep wounds mend swiftly.", flavor:"Your flesh closes like a well-told secret."},
    {name:"Twin Strike", desc:"You can strike twice in one action.", flavor:"Your second cut rides the first."},
    {name:"Spellbreaker", desc:"You tear through active curses and spells.", flavor:"Knots of magic unravel at your touch."},
    {name:"Flash Sprint", desc:"You cross short distances in a blink.", flavor:"The world lags; your feet do not."},
    {name:"Astral Sight", desc:"You see spirits, illusions, and magical flows.", flavor:"Reality shows you its underlines."},
    {name:"Energy Conductor", desc:"You redirect foreign energy into offense.", flavor:"Power is a river; you change its bed."},
    {name:"Aura of Fear", desc:"Weak foes may collapse from your presence.", flavor:"Tremor spreads before your shadow."},
    {name:"Weapon Mastery", desc:"Any weapon feels like well-practiced art.", flavor:"Balance and edge greet you by name."},
    {name:"Ward Field", desc:"An aura dampens physical attacks.", flavor:"Force diffuses around your outline."},
    {name:"Elemental Strike", desc:"One attack is empowered by an element.", flavor:"Your blow borrows thunder."},
    {name:"Totem Power", desc:"Ancestral spirits lend you might.", flavor:"Old hands steady yours from beyond."},
    {name:"Bloodline Awakened (Major)", desc:"Your heritage manifests strongly.", flavor:"History wears your face for a while."},
    {name:"Minor Power Zone", desc:"You create a field that amplifies abilities.", flavor:"Space itself nods to your intent."},
    {name:"Premonition", desc:"Your eyes read movements like a book.", flavor:"The future can’t help leaking hints."},
    {name:"Energy Carapace (Major)", desc:"Near-impervious for a short span.", flavor:"You harden into the idea of survival."}
  ],
  s: [
    {name:"Fragment of Immortality", desc:"You cannot be finally slain.", flavor:"Death misplaces your name."},
    {name:"Divine Spark", desc:"Once per session, perform a miracle.", flavor:"For a moment, the rules ask your permission."},
    {name:"True Sight", desc:"You perceive illusions, lies, and possible futures.", flavor:"Truth shines with a color you can’t describe."},
    {name:"Step Between Worlds", desc:"Open rifts and traverse realms.", flavor:"Distance becomes a polite suggestion."},
    {name:"Time Distortion", desc:"Freeze or slow time for seconds.", flavor:"You move while the seconds catch their breath."},
    {name:"Awakened Dragonblood", desc:"Brief draconic transformation.", flavor:"Ash and thunder remember your shape."},
    {name:"Fatebond", desc:"Bend destiny once per session.", flavor:"Threads rearrange when you pull."},
    {name:"Sovereign of Souls", desc:"Command spirits, dead, or demonic beings.", flavor:"Your will casts long shadows in the beyond."},
    {name:"Worldwalker", desc:"Enter planes or dreamscapes at will.", flavor:"Doors appear where you look long enough."},
    {name:"Legend Form", desc:"Your body becomes mythic; all powers surge.", flavor:"You step into the story others tell later."}
  ],
  random: [
    {name:"Soul Scar", desc:"An ancient wound marked you with foreign power—sometimes boon, sometimes bane.", flavor:"Old pain leaves bright fingerprints."},
    {name:"Cursed Breath", desc:"Your breath is uncanny—animals avoid you, spirits pay attention.", flavor:"Frost and incense mingle in every exhale."},
    {name:"Stellar Shard", desc:"A fragment from another age sleeps within you. Its effects are unknown.", flavor:"A quiet star lodges beneath your ribs."},
    {name:"Dreamwalker", desc:"In dreams you visit places that feel real—and sometimes bring things back.", flavor:"You wake with sand from nowhere."},
    {name:"Shadow Double", desc:"At times your shadow moves on its own—helpful, or treacherous.", flavor:"Your silhouette keeps its own counsel."},
    {name:"Blood Hunger", desc:"The scent of blood hones your senses—but frays your control.", flavor:"Clarity sharpens to a dangerous edge."},
    {name:"Whisper of the Deep", desc:"Voices from abysses share secrets—truth uncertain.", flavor:"Echoes rise from places that don’t have floors."},
    {name:"Lost Time", desc:"You miss seconds or minutes, returning with stray knowledge.", flavor:"You find answers in pockets of absence."},
    {name:"Ash Mark", desc:"A mystic sigil on your skin glows when danger nears.", flavor:"Warning blooms like ember under the skin."},
    {name:"Eye of the Other", desc:"One eye sometimes sees what others cannot—possible futures, ancient times.", flavor:"History and tomorrow trade places in your gaze."}
  ]
};
